- name: Download Content Database
  hosts: firewall-cluster
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Download Content Database
    panos_op:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      cmd: request content upgrade download latest
    register: result

  - name: returned output in the default JSON format
    debug: msg='{{ result.stdout }}'

  - name: returned output in the XML format
    debug: msg='{{ result.stdout_xml }}'
