- name: Updating Firewall
  hosts: firewall-a
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Install PAN-OS and restart
    panos_software:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      #API user doesn't have superuser permissions even when configured
      #api_key: '{{ api_key }}'
      version: '8.0.6'
      restart: true
